### ISSUE TITLE
Use the full pipeline output on the wsp tests

### ISSUE THREAD

**Issue by david-caro** [inspirehep/hepcrawl#111]
As we do on arxiv, we should be using the full pipeline output instead of just the spider, that way all the tests will be really checking that the produced data is schema compliant.

**Comment by david-caro** [comment]
Please @spirosdelviniotis put this on the top of your queue, as I'd like to get this merged before the other prs that depend on #95

**Comment by spirosdelviniotis** [comment]
I am on it now!
