### ISSUE TITLE
Unit tests: mock the connection to external services

### ISSUE THREAD

**Issue by david-caro** [inspirehep/hepcrawl#120]
- [x] tests/unit/test_alpha.py
- [x] tests/unit/test_aps.py
- [x] tests/unit/test_arxiv_all.py
- [x] tests/unit/test_arxiv_single.py
- [x] tests/unit/test_base.py
- [x] tests/unit/test_brown.py
- [x] tests/unit/test_dnb.py
- [x] tests/unit/test_edp.py
- [x] tests/unit/test_elsevier.py
- [x] tests/unit/test_hindawi.py
- [x] tests/unit/test_infn.py
- [x] tests/unit/test_magic.py
- [x] tests/unit/test_mit.py
- [x] tests/unit/test_phenix.py
- [x] tests/unit/test_phil.py
- [x] tests/unit/test_pipelines.py
- [x] tests/unit/test_pos.py
- [x] tests/unit/test_t2k.py
- [x] tests/unit/test_utils.py
- [x] tests/unit/test_world_scientific.py

**Comment by spirosdelviniotis** [comment]
Closes via #146
