### ISSUE TITLE
loader: calculate "number_of_pages"

### ISSUE THREAD

**Issue by fschwenn** [inspirehep/hepcrawl#170]
Calculate "number_of_pages" from "page_start" and "page_end"

## Expected Behavior
If the number of pages are not explicitly in the metadata and the journal has old school pagination, we can calculate
number_of_pages = page_end - page_start + 1
(don't forget the +1!)

## Current Behavior
At DESY we do this. Some harvesting-kit-codes have this as well.

## Context:
We will have to write a lot of spiders. It would save time, if we would not have to add such a line to every second spider.

**Comment by michamos** [comment]
this is already implemented in the `LiteratureBuilder`: https://github.com/inspirehep/inspire-schemas/blob/5a286d9673457b347c42bd8c85082a3107b8463d/inspire_schemas/builders/literature.py#L491-L497
