### ISSUE TITLE
Handling "on behalf of the ATLAS Collaboration"

### ISSUE THREAD

**Issue by kaplun** [inspirehep/hepcrawl#176]
## Expected Behavior
Record http://export.arxiv.org/oai2?verb=GetRecord&identifier=oai:arXiv.org:1709.04381&metadataPrefix=arXivRaw in the arXiv spider contains:
```xml
<authors>
Leonid Serkin (on behalf of the ATLAS Collaboration)
</authors>
```
This should lead to: 
```json
"collaborations": [{"value": "ATLAS"}]
```

## Current Behavior
Currently, looks like the record currently running on legacy is parsing this as
```json
"collaborations": [{"value": "on behalf of the ATLAS"}]
```

## Context
Note: the current behavior is reproducible on legacy code. It might very well be that the hepcrawl code is already working nicely in this respect (then a test could be added to ensure this behavior).

**Comment by michamos** [comment]
I would suggest doing this kind of normalization in the literature builder instead of the spiders.

**Comment by kaplun** [comment]
Isn't this very specific of how users are filling forms in arXiv? Other publisher might have different conventions...

**Comment by michamos** [comment]
this is from a WSP record:
```xml
<on-behalf-of> on behalf of the <italic>CERN</italic> n_TOF collaboration</on-behalf-of>
```
so not specific to arXiv I would say, but to conference proceedings.

**Comment by michamos** [comment]
This is handled already in Hepcrawl, and will be handled in the builder after inspirehep/inspire-schemas#242.
