### ISSUE TITLE
Use self.logger instead of deprecated self.log in spiders

### ISSUE THREAD

**Issue by michamos** [inspirehep/hepcrawl#183]
## Expected Behavior

[`scrapy.log` has been deprecated](https://doc.scrapy.org/en/latest/topics/logging.html) and `self.logger` should be used instead inside the spiders.

## Steps to Reproduce (for bugs)

1.
2.

**Comment by szymonlopaciuk** [comment]
I don't think we actually use the deprecated `scrapy.log` anywhere in the code? We do use `self.log` (where self is a spider), however that seems to only be a shorthand to the new way https://github.com/scrapy/scrapy/blob/master/scrapy/spiders/__init__.py#L40-L47, via native logging. Do we want to unify the code to only use `logger` directly in all cases (which has the advantage of explicitly specifying the log level)?
