### ISSUE TITLE
Move all the logic from the pipelines `process_item` method to the spiders

### ISSUE THREAD

**Issue by david-caro** [inspirehep/hepcrawl#62]
There's no need for an extra internal format anymore, thus, we can move/remove the logic needed to transform from the implicit `internal` json format (as generated by the spiders) to the hep one, as the json generated by the spiders should be already hep-correct.

**Comment by StellaCh** [comment]
Is this still relevant @david-caro ?

**Comment by david-caro** [comment]
Not really, closing (it's "embedded" in the tasks for cleaning/rewriting the current spiders).
