### ISSUE TITLE
Move to inspire-schemas ~4.0

### ISSUE THREAD

**Issue by david-caro** [inspirehep/hepcrawl#79]
A new 3.0 version of the schemas has been released, we should adapt to it.

**Comment by david-caro** [comment]
@rikirenz fyi

**Comment by kaplun** [comment]
Woah! Already 3.0?

**Comment by david-caro** [comment]
Yep, with semantic versioning forces you to bump versions quite quick, specially if you are not stable ;)

**Comment by david-caro** [comment]
Depends on #80
